service: graphql

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    keepOutputDirectory: true
    includeModules:
      packagePath: '../../package.json'

provider:
  name: aws
  runtime: nodejs14.x
  profile: pratik-aws-account

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
